### Data Preparation and Merging

In [73]:
import pandas as pd
import os

In [74]:
os.makedirs("prepared_dataset", exist_ok=True)

## Hourly Steps dataset

In [2]:
Steps_hr_1 = pd.read_csv("../archive/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/hourlySteps_merged.csv")
Steps_hr_2 = pd.read_csv("../archive/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv")

In [3]:
Steps_hr = pd.concat([Steps_hr_1, Steps_hr_2], ignore_index=True) 
## Concatenate the datasets

In [4]:
print(Steps_hr.shape)

Steps_hr.head()

(46183, 3)

           Id           ActivityHour  StepTotal
0  1503960366  3/12/2016 12:00:00 AM          0
1  1503960366   3/12/2016 1:00:00 AM          0
2  1503960366   3/12/2016 2:00:00 AM          0
3  1503960366   3/12/2016 3:00:00 AM          0
4  1503960366   3/12/2016 4:00:00 AM          0

In [5]:
print(Steps_hr.columns)

Index(['Id', 'ActivityHour', 'StepTotal'], dtype='object')

In [6]:
Steps_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46183 entries, 0 to 46182
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            46183 non-null  int64
 1   ActivityHour  46183 non-null  object
 2   StepTotal     46183 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [7]:
Steps_hr.rename(columns={
    'ActivityHour': 'datetime',

}, inplace=True)

In [8]:

Steps_hr['datetime'] = pd.to_datetime(Steps_hr['datetime'], format='%m/%d/%Y %I:%M:%S %p')

In [9]:
Steps_hr.head()

           Id            datetime  StepTotal
0  1503960366 2016-03-12 00:00:00          0
1  1503960366 2016-03-12 01:00:00          0
2  1503960366 2016-03-12 02:00:00          0
3  1503960366 2016-03-12 03:00:00          0
4  1503960366 2016-03-12 04:00:00          0

## Hourly Sleep Dataset

In [10]:
sleep_1= pd.read_csv("../archive/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/minuteSleep_merged.csv")
sleep_2 = pd.read_csv("../archive/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/minuteSleep_merged.csv")

In [34]:
sleep = pd.concat([sleep_1, sleep_2], ignore_index=True)

In [35]:
print(sleep.shape)

sleep.head()

(387080, 4)

           Id                  date  value        logId
0  1503960366  3/13/2016 2:39:30 AM      1  11114919637
1  1503960366  3/13/2016 2:40:30 AM      1  11114919637
2  1503960366  3/13/2016 2:41:30 AM      1  11114919637
3  1503960366  3/13/2016 2:42:30 AM      1  11114919637
4  1503960366  3/13/2016 2:43:30 AM      1  11114919637

In [36]:
sleep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387080 entries, 0 to 387079
Data columns (total 4 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Id      387080 non-null  int64
 1   date    387080 non-null  object
 2   value   387080 non-null  int64
 3   logId   387080 non-null  int64
dtypes: int64(3), object(1)
memory usage: 11.8+ MB

In [37]:
sleep.rename(columns={
    'date': 'datetime',

}, inplace=True)

In [38]:


sleep['datetime'] = pd.to_datetime(sleep['datetime'])


sleep['datetime'] = sleep['datetime'].dt.floor('H')

sleep_hourly = sleep.groupby(['Id', 'datetime', 'value']).size().unstack(fill_value=0).reset_index()


sleep_hourly.columns.name = None
sleep_hourly.rename(columns={1: 'asleep_min', 2: 'restless_min', 3: 'awake_min'}, inplace=True)


sleep_hourly['total_sleep_min'] = sleep_hourly.get('asleep_min', 0) + sleep_hourly.get('restless_min', 0)

/var/folders/36/sl5hb49j1w19_xpzyhm1w6dc0000gn/T/ipykernel_869/1343765119.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  sleep['datetime'] = sleep['datetime'].dt.floor('H')  # round down to the nearest hour

In [39]:
sleep.head()

           Id            datetime  value        logId
0  1503960366 2016-03-13 02:00:00      1  11114919637
1  1503960366 2016-03-13 02:00:00      1  11114919637
2  1503960366 2016-03-13 02:00:00      1  11114919637
3  1503960366 2016-03-13 02:00:00      1  11114919637
4  1503960366 2016-03-13 02:00:00      1  11114919637

## Hourly Calories

In [40]:
Calories_hr_1 = pd.read_csv("../archive/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/hourlyCalories_merged.csv")
Calories_hr_2 = pd.read_csv("../archive/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv")

In [41]:
Calories_hr = pd.concat([Calories_hr_1, Calories_hr_2], ignore_index=True)

In [42]:
Calories_hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46183 entries, 0 to 46182
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            46183 non-null  int64
 1   ActivityHour  46183 non-null  object
 2   Calories      46183 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.1+ MB

In [43]:
print(Calories_hr.shape)

Calories_hr.head()

(46183, 3)

           Id           ActivityHour  Calories
0  1503960366  3/12/2016 12:00:00 AM        48
1  1503960366   3/12/2016 1:00:00 AM        48
2  1503960366   3/12/2016 2:00:00 AM        48
3  1503960366   3/12/2016 3:00:00 AM        48
4  1503960366   3/12/2016 4:00:00 AM        48

In [44]:
Calories_hr.rename(columns={
    'ActivityHour': 'datetime',

}, inplace=True)

In [45]:
Calories_hr['datetime'] = pd.to_datetime(Calories_hr['datetime'])

/var/folders/36/sl5hb49j1w19_xpzyhm1w6dc0000gn/T/ipykernel_869/1500086064.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Calories_hr['datetime'] = pd.to_datetime(Calories_hr['datetime'])

In [46]:
Calories_hr.head()

           Id            datetime  Calories
0  1503960366 2016-03-12 00:00:00        48
1  1503960366 2016-03-12 01:00:00        48
2  1503960366 2016-03-12 02:00:00        48
3  1503960366 2016-03-12 03:00:00        48
4  1503960366 2016-03-12 04:00:00        48

## Hourly Heart Rate

In [47]:

hr_1 = pd.read_csv("../archive/mturkfitbit_export_3.12.16-4.11.16/Fitabase Data 3.12.16-4.11.16/heartrate_seconds_merged.csv")
hr_2 = pd.read_csv("../archive/mturkfitbit_export_4.12.16-5.12.16/Fitabase Data 4.12.16-5.12.16/heartrate_seconds_merged.csv")

In [48]:
hr = pd.concat([hr_1, hr_2], ignore_index=True)

In [49]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3638339 entries, 0 to 3638338
Data columns (total 3 columns):
 #   Column  Dtype
---  ------  -----
 0   Id      int64
 1   Time    object
 2   Value   int64
dtypes: int64(2), object(1)
memory usage: 83.3+ MB

In [50]:
print(hr.shape)

hr.head()

(3638339, 3)

           Id                 Time  Value
0  2022484408  4/1/2016 7:54:00 AM     93
1  2022484408  4/1/2016 7:54:05 AM     91
2  2022484408  4/1/2016 7:54:10 AM     96
3  2022484408  4/1/2016 7:54:15 AM     98
4  2022484408  4/1/2016 7:54:20 AM    100

In [51]:
hr.rename(columns={
    'Time': 'datetime',

}, inplace=True)

In [52]:

hr['datetime'] = pd.to_datetime(hr['datetime'])


hr['datetime'] = hr['datetime'].dt.floor('H')

hr_hourly = hr.groupby(['Id', 'datetime'])['Value'].mean().reset_index()


hr_hourly.rename(columns={'Value': 'hourly_heart_rate'}, inplace=True)

/var/folders/36/sl5hb49j1w19_xpzyhm1w6dc0000gn/T/ipykernel_869/2491650497.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hr['datetime'] = hr['datetime'].dt.floor('H')

In [53]:

merged = pd.merge(Steps_hr, sleep_hourly, on=['Id', 'datetime'], how='outer')
merged = pd.merge(merged, hr_hourly, on=['Id', 'datetime'], how='outer')
merged = pd.merge(merged, Calories_hr, on=['Id', 'datetime'], how='outer')

In [54]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46566 entries, 0 to 46565
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 46566 non-null  int64
 1   datetime           46566 non-null  datetime64[ns]
 2   StepTotal          46533 non-null  float64
 3   asleep_min         7500 non-null   float64
 4   restless_min       7500 non-null   float64
 5   awake_min          7500 non-null   float64
 6   total_sleep_min    7500 non-null   float64
 7   hourly_heart_rate  8640 non-null   float64
 8   Calories           46533 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1)
memory usage: 3.2 MB

In [55]:
merged.head()

,Id,datetime,StepTotal,asleep_min,restless_min,awake_min,total_sleep_min,hourly_heart_rate,Calories
0,1503960366,2016-03-12 00:00:00,0.0,NaN,NaN,NaN,NaN,NaN,48.0
1,1503960366,2016-03-12 01:00:00,0.0,NaN,NaN,NaN,NaN,NaN,48.0
2,1503960366,2016-03-12 02:00:00,0.0,NaN,NaN,NaN,NaN,NaN,48.0
3,1503960366,2016-03-12 03:00:00,0.0,NaN,NaN,NaN,NaN,NaN,48.0
4,1503960366,2016-03-12 04:00:00,0.0,NaN,NaN,NaN,NaN,NaN,48.0

In [57]:
merged.shape

(46566, 9)

In [58]:
merged.isnull().sum()

Id                       0
datetime                 0
StepTotal               33
asleep_min           39066
restless_min         39066
awake_min            39066
total_sleep_min      39066
hourly_heart_rate    37926
Calories                33
dtype: int64

In [59]:
merged.fillna({'StepTotal': 0, 'total_sleep_min': 0, 'Calories':0 }, inplace=True)

In [131]:
merged.isnull().sum()

Id                       0
datetime                 0
StepTotal                0
asleep_min           20325
restless_min         20325
awake_min            20325
total_sleep_min          0
hourly_heart_rate    21573
Calories                 0
dtype: int64

In [60]:
merged = merged.drop(columns=['asleep_min', 'restless_min', 'awake_min' ])

In [61]:
merged.isnull().sum()

Id                       0
datetime                 0
StepTotal                0
total_sleep_min          0
hourly_heart_rate    37926
Calories                 0
dtype: int64

In [62]:
df_clean = merged.dropna()

In [63]:
df_clean.isnull().sum()

Id                   0
datetime             0
StepTotal            0
total_sleep_min      0
hourly_heart_rate    0
Calories             0
dtype: int64

In [66]:
df_clean.shape

(8640, 6)

In [67]:
df_clean.duplicated().sum()

np.int64(141)

In [68]:
df_clean = df_clean.drop_duplicates()

In [70]:
df_clean.shape

(8499, 6)

In [71]:

df_clean.to_csv("prepared_dataset/Hourly_final_cleaned.csv", index=False)
df_clean.head()

,Id,datetime,StepTotal,total_sleep_min,hourly_heart_rate,Calories
7879,2022484408,2016-04-01 07:00:00,123.0,0.0,100.326531,78.0
7880,2022484408,2016-04-01 08:00:00,440.0,0.0,71.396419,115.0
7881,2022484408,2016-04-01 09:00:00,4994.0,0.0,121.205323,427.0
7882,2022484408,2016-04-01 10:00:00,2926.0,0.0,97.129771,248.0
7883,2022484408,2016-04-01 11:00:00,0.0,0.0,90.000000,62.0